### ISSUE TITLE
What is the difference between files initialize_Guelph_0.uwg, ..._1.uwg, ..._2.uwg for Month,1 ? 

### ISSUE THREAD

**Issue by rarygit** [AmirAAliabadi/VCWGv1.4.4#1]
Thanks Amir for uploading VCWG version 1.4.4

Both scripts run OK on Python 2.18

I have one question:

For the following parameter files: initialize_Guelph_0.uwg, initialize_Guelph_1.uwg, initialize_Guelph_2.uwg
What is the difference in the Simulation parameters at line 230: Month,1, ?
  
#param_filename = "initialize_Guelph_0.uwg"         # .uwg file name, Month 1
#param_filename = "initialize_Guelph_1.uwg"         # .uwg file name, Month 1
#param_filename = "initialize_Guelph_2.uwg"         # .uwg file name, Month 1
#param_filename = "initialize_Guelph_3.uwg"         # .uwg file name, Month 2
#param_filename = "initialize_Guelph_4.uwg"         # .uwg file name, Month 3
#param_filename = "initialize_Guelph_5.uwg"         # .uwg file name, Month 4
#param_filename = "initialize_Guelph_6.uwg"         # .uwg file name, Month 5
#param_filename = "initialize_Guelph_7.uwg"         # .uwg file name, Month 6
param_filename = "initialize_Guelph_8.uwg"         # .uwg file name, Month 7
#param_filename = "initialize_Guelph_9.uwg"         # .uwg file name, Month 8
#param_filename = "initialize_Guelph_10.uwg"         # .uwg file name, Month 9
#param_filename = "initialize_Guelph_11.uwg"         # .uwg file name, Month 10
#param_filename = "initialize_Guelph_12.uwg"         # .uwg file name, Month 11 

And one comment.

In the User Manual, to retrieve ERA5 climate data in epw and csv formats, it might be helpful to suggest using the website www.shinyweatherdata.com

![guelph](https://user-images.githubusercontent.com/16574504/126954919-c4bb6112-4ca6-4c1d-9c62-6edd1b232f5c.jpg)

**Comment by AmirAAliabadi** [comment]
Hello rarygit,

Thank you for your interest and I am glad the software is running on your computer. I added the website www.shinyweatherdata.com to the instruction guide. Thank you for the suggestion.

Regarding initialize_Guelph_0.uwg, it is the initialization file to run the software in January 2015 for the non-optimized case (0). The subsequent files initialize_Guelph_1.uwg to initialize_Guelph_12.uwg are the initialization files to run the software for each of the months January to December in 2015 for the optimized case (8). 

Lines 230, 231, 232 contain the starting month, starting day, and the duration of the simulation in number of days. For each month, it is desired to start the simulation 3 days before the start of the month and then discard the first 3 days of data as spin up data. For example, to simulate Feburary, one can start from Month = 1 (January), Day = 29 (3 days before start of February), for nDay = 31 (28 days in February plus 3 days for spin up). The January simulation is an exception because the ERA5 dataset only contains data in 2015, so for January we cannot start 3 days earlier in 2014.

Regards,
Amir A. Aliabadi

**Comment by rarygit** [comment]
Thanks Amir for the explanation above, that was helpful!

Along with re-reading the user manual and your referenced article "How Much Building Renewable Energy Is Enough?", I was able to understand the difference between case 1 (initialize_Guelph_0.uwg) and case 8 (using 1 to 12 uwg initialize files).

For example, looking at file initialize_Guelph_11.uwg:
I understand from your explanation the meaning of Day,29, and nDay,33

And I think I understand how that relates to these numbers in the description, after the hash # e.g. 1-29-26-29-28- ... etc
,  # starting day (1-31) J-F-M-A-M-J-J-A-S-O-N-D: 1-29-26-29-28-29-28-29-29-28-29-28
,  # number of days to run simulation J-F-M-A-M-J-J-A-S-O-N-D: 31-31-34-33-34-33-34-34-33-34-33-34

"Regarding initialize_Guelph_0.uwg, it is the initialization file to run the software in January 2015 for the non-optimized case (0)"
"The serial mode allows running the model for 12 consecutive months, requiring 12 initialization files." (User Manual)

So if I want to run case (0) using python script "VCWGv1.4.4Serial.py" for 12 months of the year, do I need to create 12 initialisation files based on the non-optimised file "initialize_('my place')_0.uwg" ?

**Comment by AmirAAliabadi** [comment]
My pleasure. That is the right understanding. If you want to run a standard case with no renewable/alternative energy, then you have two options. 

1) You can run VCWG v1.3.2 (Moradi et al. 2021) which is deposited in Zenodo.org. This was my approach for the referenced article "How Much Building Renewable Energy Is Enough?". 

2) Alternatively you can disable the renewable/alternative energy options in VCWG v1.4.4. To do this, it is preferable to go with a reference building under "VCWG v1.4.4\resources\DOERefBuildings" with an ASHRAE zone other than "Guelph 5A" (i.e. you should not have building material as wall "EPPWall" and roof "EPPRoof"). For instance you can chose other ASHRAE zones for "Boulder 5B". This requires changing from "zone,17," to "zone,12," in the initialization file. You should change the ventilation and infiltration rates for the appropriate files in "BLDX_ZoneSummary.xls" in directories "VCWG v1.4.4\resources\DOERefBuildings\BLD1" through
"VCWG v1.4.4\resources\DOERefBuildings\BLD16" to reflect the correct building type. Also, to eliminate renewable/alternative energy,  many parameters can be set to a very small, but non-zero, number, in each of the 12 initialization files. These are the solar thermal collector area, PV area, wind turbine area, thermal energy storage volume, and PCM volume: e.g. "A_st, 0.01,", "A_pv, 0.01", "A_wt, 0.01", "V_bites, 0.01", "V_pcm, 0.01". This allows the model to perform the calculations as usual but not divide by zero, etc. These settings essentially eliminate the renewable/alternative energy systems for the model, and you can interpret the building performance metrics as that of a basic building.

Feel free to try option 2 and let me know how successful it will be. I never tried it this way, but I am curious to know.

**Comment by rarygit** [comment]
OK, I will try modifying the renewable/alternative energy options in VCWG v1.4.4, as you suggest.
It will be good to test the model.

This will be a separate discussion to this issue, which is answered and I think can now be closed.
